# 安装jdk7

- name: transfer jdk-7u80-linux-x64.tar.gz to dest client's /usr/local directory
  copy: src=/app/ansible/files/jdk-7u80-linux-x64.tar.gz dest=/usr/local
        owner=root mode=0644

- name: extract jdk-7u80-linux-x64.tar.gz
  shell: tar -zxf /usr/local/jdk-7u80-linux-x64.tar.gz -C /usr/local
  args:
    creates: /usr/local/jdk1.7

- name: mv name
  shell: mv /usr/local/jdk1.7.0_80 /usr/local/jdk1.7
  args:
    creates: /usr/local/jdk1.7

- name: chown jdk
  shell: chown root.root /usr/local/jdk1.7/ -R